family: "tag36h11"
nthreads: 1
quad_decimate: 1.0
quad_sigma: 0.0
refine_edges: 1
decode_sharpening: 0.25
debug: 0


num_imgs: 30
checkerboard:
  rows: 9
  cols: 6

intrinsics:
  f: 
  cx:
  cy:
  k1:
  k2:
  k3:
  p1:
  p2: