family: tag36h11
nthreads: 1
quad_decimate: 1.0
quad_sigma: 0.0
refine_edges: 1
decode_sharpening: 0.25
debug: 0
num_imgs: 30
checkerboard:
  rows: 9
  cols: 6
intrinsics:
  fx: 608.5979683227014
  fy: null
  cx: 338.7499421864549
  cy: 224.22662489348707
  k1: 0.056261003357531404
  k2: -0.09489812525710707
  k3: 0.5020962903206452
  p1: -0.003777552555555347
  p2: 0.004925255659135433
